services:
  mongo:
    image: mongo:latest
    container_name: mongo_dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

  javalin_app:
#    build: .
    image: cristiandelahooz/urlshortener-javalin:1.0.1
    container_name: javalin_dev
    ports:
      - "8765:8765"
      - "9876:9876"
    environment:
#      - PORT=8765
#      - PORT_GRPC=9876
      - MONGODB_URL=mongodb://admin:admin123@mongo:27017/?authSource=admin
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo

volumes:
  mongo-data: